export const loopchainAbi = [
  { type: 'function', name: 'currentLoop', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint64' }] },
  // 144-cell live grid → one uint256 (bit i = cell i is currently rented).
  { type: 'function', name: 'livePattern', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  // 16 bits per synth cell × 16 synth cells → one uint256. v1 uses bits 0-2 (pitch).
  { type: 'function', name: 'liveSynthData', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  {
    type: 'function',
    name: 'cellOwner',
    stateMutability: 'view',
    inputs: [{ type: 'uint8' }],
    outputs: [{ type: 'address' }],
  },
  {
    type: 'function',
    name: 'cellExpiryLoop',
    stateMutability: 'view',
    inputs: [{ type: 'uint8' }],
    outputs: [{ type: 'uint64' }],
  },
  {
    // Synth cells only (cellId ≥ 128). 16-bit word; bits 0-2 are the pitch.
    type: 'function',
    name: 'cellSynthData',
    stateMutability: 'view',
    inputs: [{ type: 'uint8' }],
    outputs: [{ type: 'uint16' }],
  },
  { type: 'function', name: 'rentPerLoop', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'basePrice', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'alpha', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'holdersBps', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint16' }] },
  { type: 'function', name: 'treasuryBps', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint16' }] },
  {
    type: 'function',
    name: 'maxRentDurationLoops',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint16' }],
  },
  {
    // cellData is the 16-bit synth word; for synth cells v1 stores bits 0-2
    // (pitch, 0-7) and rejects anything else. Ignored for drum cells.
    type: 'function',
    name: 'toggle',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'cellId', type: 'uint8' },
      { name: 'durationLoops', type: 'uint16' },
      { name: 'cellData', type: 'uint16' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'record',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'press',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'seriesId', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
  },
  { type: 'function', name: 'nextTokenId', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'nextSeriesId', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  // Live-grid globals frozen into each Series at record() time.
  { type: 'function', name: 'kitId', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint8' }] },
  { type: 'function', name: 'scaleId', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint8' }] },
  { type: 'function', name: 'swing', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint8' }] },
  {
    type: 'function',
    name: 'seriesOf',
    stateMutability: 'view',
    inputs: [{ type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'editionOf',
    stateMutability: 'view',
    inputs: [{ type: 'uint256' }],
    outputs: [{ type: 'uint32' }],
  },
  {
    type: 'function',
    name: 'pressPriceFor',
    stateMutability: 'view',
    inputs: [{ name: 'seriesId', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'priceForEdition',
    stateMutability: 'view',
    inputs: [{ name: 'edition', type: 'uint32' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'ownerOf',
    stateMutability: 'view',
    inputs: [{ type: 'uint256' }],
    outputs: [{ type: 'address' }],
  },
  {
    // Series snapshot. pattern/synthData are uint256; kitId/scaleId/swing are
    // the live globals frozen at record() time.
    type: 'function',
    name: 'seriesInfo',
    stateMutability: 'view',
    inputs: [{ type: 'uint256' }],
    outputs: [
      { name: 'pattern', type: 'uint256' },
      { name: 'synthData', type: 'uint256' },
      { name: 'mintedAtLoop', type: 'uint64' },
      { name: 'nextEdition', type: 'uint32' },
      { name: 'kitId', type: 'uint8' },
      { name: 'scaleId', type: 'uint8' },
      { name: 'swing', type: 'uint8' },
      { name: 'holders', type: 'address[]' },
      { name: 'cellsPerHolder', type: 'uint8[]' },
    ],
  },
  {
    type: 'function',
    name: 'loopOf',
    stateMutability: 'view',
    inputs: [{ type: 'uint256' }],
    outputs: [
      { name: 'pattern', type: 'uint256' },
      { name: 'synthData', type: 'uint256' },
      { name: 'mintedAtLoop', type: 'uint64' },
      { name: 'kitId', type: 'uint8' },
      { name: 'scaleId', type: 'uint8' },
      { name: 'swing', type: 'uint8' },
      { name: 'holders', type: 'address[]' },
      { name: 'cellsPerHolder', type: 'uint8[]' },
    ],
  },
  {
    type: 'event',
    name: 'CellRented',
    inputs: [
      { name: 'cellId', type: 'uint8', indexed: true },
      { name: 'renter', type: 'address', indexed: true },
      { name: 'expiryLoop', type: 'uint64', indexed: false },
      { name: 'cellData', type: 'uint16', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SeriesRecorded',
    inputs: [
      { name: 'seriesId', type: 'uint256', indexed: true },
      { name: 'tokenId', type: 'uint256', indexed: true },
      { name: 'recorder', type: 'address', indexed: true },
      { name: 'pattern', type: 'uint256', indexed: false },
      { name: 'synthData', type: 'uint256', indexed: false },
      { name: 'mintedAtLoop', type: 'uint64', indexed: false },
      { name: 'holdersCount', type: 'uint256', indexed: false },
      { name: 'pricePaid', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SeriesPressed',
    inputs: [
      { name: 'seriesId', type: 'uint256', indexed: true },
      { name: 'tokenId', type: 'uint256', indexed: true },
      { name: 'presser', type: 'address', indexed: true },
      { name: 'edition', type: 'uint32', indexed: false },
      { name: 'pricePaid', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  // Royalty (pull-claim, series-keyed). depositRoyalty/claimedSeries getters let the
  // UI compute a holder's claimable share without a dedicated view function.
  {
    type: 'function',
    name: 'royaltyDepositedSeries',
    stateMutability: 'view',
    inputs: [{ name: 'seriesId', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'royaltyClaimedSeries',
    stateMutability: 'view',
    inputs: [
      { name: 'seriesId', type: 'uint256' },
      { name: 'holder', type: 'address' },
    ],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'claimRoyalty',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'seriesId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'event',
    name: 'RoyaltyClaimed',
    inputs: [
      { name: 'seriesId', type: 'uint256', indexed: true },
      { name: 'holder', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
] as const

export const usdmAbi = [
  {
    type: 'function',
    name: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'allowance',
    stateMutability: 'view',
    inputs: [{ type: 'address' }, { type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'approve',
    stateMutability: 'nonpayable',
    inputs: [{ type: 'address' }, { type: 'uint256' }],
    outputs: [{ type: 'bool' }],
  },
] as const
