export const loopchainAbi = [
  { type: 'function', name: 'currentLoop', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint64' }] },
  { type: 'function', name: 'livePattern', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint64' }] },
  { type: 'function', name: 'livePitches', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint64' }] },
  {
    type: 'function',
    name: 'cellOwner',
    stateMutability: 'view',
    inputs: [{ type: 'uint8' }],
    outputs: [{ type: 'address' }],
  },
  {
    type: 'function',
    name: 'cellExpiryLoop',
    stateMutability: 'view',
    inputs: [{ type: 'uint8' }],
    outputs: [{ type: 'uint64' }],
  },
  {
    type: 'function',
    name: 'cellPitch',
    stateMutability: 'view',
    inputs: [{ type: 'uint8' }],
    outputs: [{ type: 'uint8' }],
  },
  { type: 'function', name: 'rentPerLoop', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'basePrice', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'alpha', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'holdersBps', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint16' }] },
  { type: 'function', name: 'treasuryBps', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint16' }] },
  {
    type: 'function',
    name: 'maxRentDurationLoops',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint16' }],
  },
  {
    type: 'function',
    name: 'toggle',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'cellId', type: 'uint8' },
      { name: 'durationLoops', type: 'uint16' },
      { name: 'pitchIdx', type: 'uint8' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'record',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'press',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'seriesId', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
  },
  { type: 'function', name: 'nextTokenId', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'nextSeriesId', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  {
    type: 'function',
    name: 'seriesOf',
    stateMutability: 'view',
    inputs: [{ type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'editionOf',
    stateMutability: 'view',
    inputs: [{ type: 'uint256' }],
    outputs: [{ type: 'uint32' }],
  },
  {
    type: 'function',
    name: 'pressPriceFor',
    stateMutability: 'view',
    inputs: [{ name: 'seriesId', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'priceForEdition',
    stateMutability: 'view',
    inputs: [{ name: 'edition', type: 'uint32' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'ownerOf',
    stateMutability: 'view',
    inputs: [{ type: 'uint256' }],
    outputs: [{ type: 'address' }],
  },
  {
    type: 'function',
    name: 'seriesInfo',
    stateMutability: 'view',
    inputs: [{ type: 'uint256' }],
    outputs: [
      { name: 'pattern', type: 'uint64' },
      { name: 'pitches', type: 'uint64' },
      { name: 'mintedAtLoop', type: 'uint64' },
      { name: 'nextEdition', type: 'uint32' },
      { name: 'holders', type: 'address[]' },
      { name: 'cellsPerHolder', type: 'uint8[]' },
    ],
  },
  {
    type: 'function',
    name: 'loopOf',
    stateMutability: 'view',
    inputs: [{ type: 'uint256' }],
    outputs: [
      { name: 'pattern', type: 'uint64' },
      { name: 'pitches', type: 'uint64' },
      { name: 'mintedAtLoop', type: 'uint64' },
      { name: 'holders', type: 'address[]' },
      { name: 'cellsPerHolder', type: 'uint8[]' },
    ],
  },
  {
    type: 'event',
    name: 'CellRented',
    inputs: [
      { name: 'cellId', type: 'uint8', indexed: true },
      { name: 'renter', type: 'address', indexed: true },
      { name: 'expiryLoop', type: 'uint64', indexed: false },
      { name: 'pitchIdx', type: 'uint8', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SeriesRecorded',
    inputs: [
      { name: 'seriesId', type: 'uint256', indexed: true },
      { name: 'tokenId', type: 'uint256', indexed: true },
      { name: 'recorder', type: 'address', indexed: true },
      { name: 'pattern', type: 'uint64', indexed: false },
      { name: 'pitches', type: 'uint64', indexed: false },
      { name: 'mintedAtLoop', type: 'uint64', indexed: false },
      { name: 'holdersCount', type: 'uint256', indexed: false },
      { name: 'pricePaid', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SeriesPressed',
    inputs: [
      { name: 'seriesId', type: 'uint256', indexed: true },
      { name: 'tokenId', type: 'uint256', indexed: true },
      { name: 'presser', type: 'address', indexed: true },
      { name: 'edition', type: 'uint32', indexed: false },
      { name: 'pricePaid', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  // Royalty (pull-claim, series-keyed). depositRoyalty/claimedSeries getters let the
  // UI compute a holder's claimable share without a dedicated view function.
  {
    type: 'function',
    name: 'royaltyDepositedSeries',
    stateMutability: 'view',
    inputs: [{ name: 'seriesId', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'royaltyClaimedSeries',
    stateMutability: 'view',
    inputs: [
      { name: 'seriesId', type: 'uint256' },
      { name: 'holder', type: 'address' },
    ],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'claimRoyalty',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'seriesId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'event',
    name: 'RoyaltyClaimed',
    inputs: [
      { name: 'seriesId', type: 'uint256', indexed: true },
      { name: 'holder', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
] as const

export const usdmAbi = [
  {
    type: 'function',
    name: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'allowance',
    stateMutability: 'view',
    inputs: [{ type: 'address' }, { type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'approve',
    stateMutability: 'nonpayable',
    inputs: [{ type: 'address' }, { type: 'uint256' }],
    outputs: [{ type: 'bool' }],
  },
] as const
